bootstrap:
  # Used by product-catalog-task
  productCatalog:
    productTypes:
      - productKindName: "currentAccount"
        productTypeName: "current-account"
        typeName: "Current Account"
        externalProductKindId: "kind1"
        externalProductId: "current-account"
      - productKindName: "savingsAccount"
        productTypeName: "savings-account"
        typeName: "Savings Accounts"
        externalProductKindId: "kind2"
        externalProductId: "savings-account"
      - productKindName: "Loan"
        productTypeName: "loans-account"
        typeName: "Loans Accounts"
        externalProductKindId: "kind5"
        externalProductId: "loans-account"
  # Used by legal-entity-bootstrap-task
  legalEntity:
    name: "Moustache Bank"
    realmName: "backbase"
    externalId: "moustache-bank"
    legalEntityType: "BANK"
    referenceJobRoles:
      - name: "Entitlements - Manager"
        description: "Full Entitlements administration."
        functionGroups:
          - name: "Manage Entitlements"
            functions:
              - functionId: "1019"
                name: "Manage Data Groups"
                privileges:
                  - privilege: "view"
                  - privilege: "create"
                  - privilege: "edit"
                  - privilege: "delete"
              - functionId: "1020"
                name: "Manage Function Groups"
                privileges:
                  - privilege: "view"
                  - privilege: "create"
                  - privilege: "edit"
                  - privilege: "delete"
              - functionId: "1010"
                name: "Manage Users"
                privileges:
                  - privilege: "view"
              - functionId: "1009"
                name: "Assign Permissions"
                privileges:
                  - privilege: "view"
                  - privilege: "create"
                  - privilege: "edit"
              - functionId: "1028"
                name: "Manage Service Agreements"
                privileges:
                  - privilege: "view"
                  - privilege: "create"
                  - privilege: "edit"
                  - privilege: "delete"
              - functionId: "1119"
                name: "Manage Self-approve Permissions"
                privileges:
                  - privilege: "view"
              - functionId: "1007"
                name: "Assign Users"
                privileges:
                  - privilege: "view"
                  - privilege: "create"
                  - privilege: "edit"
              - functionId: "1035"
                name: "Manage User Profiles"
                privileges:
                  - privilege: "view"
                  - privilege: "edit"
              - functionId: "1011"
                name: "Manage Legal Entities"
                privileges:
                  - privilege: "view"
                  - privilege: "create"
                  - privilege: "edit"
                  - privilege: "delete"
              - functionId: "1034"
                name: "Manage Identities"
                privileges:
                  - privilege: "view"
                  - privilege: "create"
                  - privilege: "edit"
              - functionId: "1049"
                name: "Lock User"
                privileges:
                  - privilege: "view"
                  - privilege: "create"
                  - privilege: "edit"
              - functionId: "1050"
                name: "Unlock User"
                privileges:
                  - privilege: "view"
                  - privilege: "create"
                  - privilege: "edit"
              - functionId: "1084"
                name: "Revoke access"
                privileges:
                  - privilege: "create"
      - name: "Retail User"
        description: "Retail User Permissions"
        functionGroups:
          - name: "Products and Profile"
            functions:
              - functionId: "1006"
                name: "Product Summary"
                functionCode: "product.summary"
                privileges:
                  - privilege: "view"
                  - privilege: "edit"
              - functionId: "1035"
                name: "Manage User Profiles"
                functionCode: "manage.user.profiles"
                privileges:
                  - privilege: "view"
                  - privilege: "edit"
          - name: "Transfer and Payments"
            functions:
              - functionId: "1053"
                name: "A2A Transfer"
                functionCode: "a2a.transfer"
                privileges:
                  - privilege: "view"
                  - privilege: "edit"
                  - privilege: "create"
              - functionId: "1021"
                name: "US Billpay Payments"
                functionCode: "us.billpay.payments"
                privileges:
                  - privilege: "view"
                  - privilege: "edit"
                  - privilege: "create"
              - functionId: "1071"
                name: "Payment Templates"
                functionCode: "payment.templates"
                privileges:
                  - privilege: "view"
                  - privilege: "edit"
                  - privilege: "create"
      - name: "Retail User Vip"
        description: "Retail User Vip Permissions"
        functionGroups:
          - name: "Domestic and Foreign"
            functions:
              - functionId: "1017"
                name: "US Domestic Wire"
                functionCode: "us.domestic.wire"
                privileges:
                  - privilege: "view"
                  - privilege: "edit"
                  - privilege: "create"
              - functionId: "1018"
                name: "US Foreign Wire"
                functionCode: "us.foreign.wire"
                privileges:
                  - privilege: "view"
                  - privilege: "edit"
                  - privilege: "create"

    users:
      - user:
          externalId: "admin"
          fullName: "Backbase Root Admin"
          identityLinkStrategy: "CREATE_IN_IDENTITY"
          emailAddress:
            address: "mailto:bbadmin@email.com"
          mobileNumber:
            number: "1234567890"
        referenceJobRoleNames:
          - "Entitlements - Manager"
    subsidiaries:
      - name: "Moustache Bank USA"
        realmName: "backbase"
        externalId: "moustache-bank-usa"
        legalEntityType: "BANK"
        subsidiaries:
          - name: "Sara"
            realmName: "backbase"
            externalId: "sara"
            legalEntityType: "CUSTOMER"
            users:
              - user:
                  externalId: "sara"
                  fullName: "Sara Jones"
                  identityLinkStrategy: "CREATE_IN_IDENTITY"
                  emailAddress:
                    address: "mailto:sara@email.com"
                  mobileNumber:
                    number: "1234567890"
            productGroups:
              - name: "sara-arrangements"
                users:
                  - user:
                      externalId: "sara"
                      fullName: "Sara Jones"
                      identityLinkStrategy: "CREATE_IN_IDENTITY"
                      emailAddress:
                        address: "mailto:sara@email.com"
                      mobileNumber:
                        number: "1234567890"
                    referenceJobRoleNames:
                      - "Retail User"
                      - "Retail User Vip"
                description: "Product group containing user arrangements"
                currentAccounts:
                  - externalId: "021000021"
                    BBAN: "021000021"
                    name: "Sara's Current Account 1"
                    productTypeExternalId: "current-account"
                    currency: "USD"
                    externalTransferAllowed: "true"
                    availableBalance:
                      currencyCode: "USD"
                      amount: "1055.5"
                    bookedBalance:
                      currencyCode: "USD"
                      amount: "1055.5"
                savingAccounts:
                  - externalId: "021000022"
                    BBAN: "021000022"
                    name: "Sara's Savings Account 1"
                    productTypeExternalId: "savings-account"
                    currency: "USD"
                    externalTransferAllowed: "false"
                    availableBalance:
                      currencyCode: "USD"
                      amount: "3820.2"
                    bookedBalance:
                      currencyCode: "USD"
                      amount: "3820.2"
                    accountInterestRate: "0.05"
                    termUnit: "Quarterly"
                  - externalId: "021000023"
                    BBAN: "021000023"
                    name: "Sara's Savings Account 2"
                    productTypeExternalId: "savings-account"
                    currency: "USD"
                    externalTransferAllowed: "false"
                    availableBalance:
                      currencyCode: "USD"
                      amount: "155.5"
                    bookedBalance:
                      currencyCode: "USD"
                      amount: "155.5"
                    accountInterestRate: "0.05"
                    termUnit: "Quarterly"
                  - externalId: "021000024"
                    BBAN: "021000022"
                    name: "Sara's Loans Account 1"
                    productTypeExternalId: "loans-account"
                    currency: "USD"
                    externalTransferAllowed: "false"
                    availableBalance:
                      currencyCode: "USD"
                      amount: "3820.2"
                    bookedBalance:
                      currencyCode: "USD"
                      amount: "3820.2"
                    accountInterestRate: "0.05"
                    termUnit: "Quarterly"
                  - externalId: "021000023"
                    BBAN: "021000023"
                    name: "Sara's Savings Account 2"
                    productTypeExternalId: "loans-account"
                    currency: "USD"
                    externalTransferAllowed: "false"
                    availableBalance:
                      currencyCode: "USD"
                      amount: "155.5"
                    bookedBalance:
                      currencyCode: "USD"
                      amount: "155.5"
                    accountInterestRate: "0.05"
                    termUnit: "Quarterly"
